import { createHash } from 'node:crypto';
import { mkdir, readFile, unlink, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { Inject, Injectable, Logger, type OnModuleInit } from '@nestjs/common';
import { APP_CONFIG } from '../../config/config.module';
import type { Env } from '../../config/env';
import { sanitizeFilename } from './file-validation';

export interface StoredObject {
  storageKey: string;
  sha256: string;
  sizeBytes: number;
}

// Document storage.
//
// Local filesystem, behind an interface shaped like object storage: put by key,
// get by key, delete by key. Swapping in S3 or MinIO is one class, and nothing
// that calls this changes — the API never streams a document to a client
// directly, so a presigned-URL implementation slots in the same way.
//
// The tradeoff is stated rather than hidden: this does not survive a container
// restart on ephemeral disk, and does not work across multiple API replicas. It
// is right for a single-node demo and wrong for production, and the seam is
// where it needs to be for that to be a config change.
@Injectable()
export class StorageService implements OnModuleInit {
  private readonly logger = new Logger(StorageService.name);
  private readonly root: string;

  constructor(@Inject(APP_CONFIG) config: Env) {
    this.root = path.resolve(config.STORAGE_ROOT);
  }

  async onModuleInit(): Promise<void> {
    await mkdir(this.root, { recursive: true });
    this.logger.log(`Document storage at ${this.root}`);
  }

  /**
   * Store a document and return what the database needs to reference it.
   *
   * The hash is computed here rather than by the caller, so the value recorded
   * alongside the object is provably the bytes that were written.
   */
  async put(input: { orgId: string; buffer: Buffer; filename: string }): Promise<StoredObject> {
    const sha256 = createHash('sha256').update(input.buffer).digest('hex');
    // Partitioned by org and content hash. Identical bytes land on the same
    // key, so a resubmitted resume costs no extra space.
    const storageKey = path.join(input.orgId, `${sha256}-${sanitizeFilename(input.filename)}`);

    const absolute = path.join(this.root, storageKey);
    await mkdir(path.dirname(absolute), { recursive: true });
    await writeFile(absolute, input.buffer);

    return { storageKey, sha256, sizeBytes: input.buffer.byteLength };
  }

  async get(storageKey: string): Promise<Buffer> {
    return readFile(this.resolve(storageKey));
  }

  async delete(storageKey: string): Promise<void> {
    await unlink(this.resolve(storageKey)).catch(() => undefined);
  }

  /**
   * Resolve a key to an absolute path, refusing anything that escapes the root.
   *
   * Storage keys are generated by `put` and never by a client, so this should
   * be unreachable — but a path-traversal check on a filesystem read is cheap
   * insurance against that assumption changing.
   */
  private resolve(storageKey: string): string {
    const absolute = path.resolve(this.root, storageKey);
    if (!absolute.startsWith(this.root + path.sep)) {
      throw new Error(`Refusing to read outside the storage root: ${storageKey}`);
    }
    return absolute;
  }
}
